/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/Villa.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.29164, 9.12506, -0.30577]}
        rotation={[-3.13113, 0, 0]}
        scale={[19.61409, 14.54545, 25.17979]}
        userData={{ name: "Cube.001" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials["Material.027"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_2.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_3.geometry}
          material={materials["Material.045"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Material.032"]}
        position={[0.29164, 9.12506, -0.30577]}
        rotation={[-Math.PI, 0, 0]}
        scale={[19.61409, 14.54546, 25.17979]}
        userData={{ name: "Cube.002" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Material.031"]}
        position={[2.87158, 5.07861, -12.27409]}
        scale={[1.38704, 1.27417, 1.45589]}
        userData={{ name: "Cube.003" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Material.031"]}
        position={[2.87158, 8.45795, -12.27409]}
        scale={[0.52125, 9.76312, 0.52336]}
        userData={{ name: "Cube.005" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["Material.031"]}
        position={[2.87158, 5.07861, -8.40124]}
        scale={[1.38704, 1.27417, 1.45589]}
        userData={{ name: "Cube.006" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials["Material.031"]}
        position={[2.87158, 6.79096, -10.34207]}
        rotation={[-2.105, 0, 0]}
        scale={[0.52125, 7.34602, 0.52336]}
        userData={{ name: "Cube.008" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials["Material.031"]}
        position={[2.87158, 6.79096, -10.34207]}
        rotation={[-0.9944, 0, 0]}
        scale={[0.52125, 7.34602, 0.52336]}
        userData={{ name: "Cube.009" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["Material.031"]}
        position={[2.87158, 7.98611, -10.35066]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.52125, 6.80035, 0.52336]}
        userData={{ name: "Cube.010" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["Material.031"]}
        position={[2.87158, 8.45795, -8.34676]}
        scale={[0.52125, 9.76312, 0.52336]}
        userData={{ name: "Cube.007" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["Material.031"]}
        position={[-2.25453, 5.07861, -12.27409]}
        scale={[1.38704, 1.27417, 1.45589]}
        userData={{ name: "Cube.004" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials["Material.031"]}
        position={[-2.25453, 8.45795, -12.27409]}
        scale={[0.52125, 9.76312, 0.52336]}
        userData={{ name: "Cube.011" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials["Material.031"]}
        position={[-2.25453, 5.07861, -8.40124]}
        scale={[1.38704, 1.27417, 1.45589]}
        userData={{ name: "Cube.012" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials["Material.031"]}
        position={[-2.25453, 6.79096, -10.34207]}
        rotation={[-2.105, 0, 0]}
        scale={[0.52125, 7.34602, 0.52336]}
        userData={{ name: "Cube.013" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials["Material.031"]}
        position={[-2.25453, 6.79096, -10.34207]}
        rotation={[-0.9944, 0, 0]}
        scale={[0.52125, 7.34602, 0.52336]}
        userData={{ name: "Cube.014" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials["Material.031"]}
        position={[-2.25453, 7.98611, -10.35066]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.52125, 6.80035, 0.52336]}
        userData={{ name: "Cube.015" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials["Material.031"]}
        position={[-2.25453, 8.45795, -8.34676]}
        scale={[0.52125, 9.76312, 0.52336]}
        userData={{ name: "Cube.016" }}
      />
      <group
        position={[0.33801, 11.67904, -11.21108]}
        scale={[14.18374, 0.58953, 9.19605]}
        userData={{ name: "Cube.017" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_1.geometry}
          material={materials["Material.020"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials["Material.028"]}
        position={[-19.03829, 33.2145, -63.73907]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.001" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials["Material.028"]}
        position={[-19.03829, 33.21204, -64.23537]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.002" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials["Material.028"]}
        position={[-19.03829, 33.20958, -64.73155]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.003" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle004.geometry}
        material={materials["Material.028"]}
        position={[-19.03829, 33.20712, -65.22786]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.004" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle005.geometry}
        material={materials["Material.028"]}
        position={[-19.03829, 33.20485, -65.6879]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.005" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle006.geometry}
        material={materials["Material.028"]}
        position={[-19.03829, 33.20239, -66.18421]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.006" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007.geometry}
        material={materials["Material.028"]}
        position={[-19.03829, 33.19993, -66.68039]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.007" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle008.geometry}
        material={materials["Material.028"]}
        position={[-19.03829, 33.19747, -67.1767]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.008" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle009.geometry}
        material={materials["Material.028"]}
        position={[-19.03829, 33.19503, -67.6688]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.009" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle010.geometry}
        material={materials["Material.028"]}
        position={[-19.03829, 33.19258, -68.16511]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.010" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle011.geometry}
        material={materials["Material.028"]}
        position={[-19.16205, 33.17426, -68.66682]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.011" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle012.geometry}
        material={materials["Material.029"]}
        position={[-19.00178, 35.26227, -63.7492]}
        rotation={[1.52042, 1.55192, 1.61621]}
        userData={{ name: "Circle.012" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle013.geometry}
        material={materials["Material.029"]}
        position={[-19.00136, 35.25981, -64.24551]}
        rotation={[1.52042, 1.55192, 1.61621]}
        userData={{ name: "Circle.013" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle014.geometry}
        material={materials["Material.029"]}
        position={[-19.00093, 35.25734, -64.74168]}
        rotation={[1.52042, 1.55192, 1.61621]}
        userData={{ name: "Circle.014" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle015.geometry}
        material={materials["Material.029"]}
        position={[-19.00051, 35.25488, -65.23799]}
        rotation={[1.52042, 1.55192, 1.61621]}
        userData={{ name: "Circle.015" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle016.geometry}
        material={materials["Material.029"]}
        position={[-19.00011, 35.25259, -65.69804]}
        rotation={[1.52042, 1.55192, 1.61621]}
        userData={{ name: "Circle.016" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle017.geometry}
        material={materials["Material.029"]}
        position={[-18.99969, 35.25013, -66.19434]}
        rotation={[1.52042, 1.55192, 1.61621]}
        userData={{ name: "Circle.017" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle018.geometry}
        material={materials["Material.029"]}
        position={[-18.99926, 35.24766, -66.69052]}
        rotation={[1.52042, 1.55192, 1.61621]}
        userData={{ name: "Circle.018" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle019.geometry}
        material={materials["Material.029"]}
        position={[-18.99884, 35.24519, -67.18683]}
        rotation={[1.52042, 1.55192, 1.61621]}
        userData={{ name: "Circle.019" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle020.geometry}
        material={materials["Material.029"]}
        position={[-18.99842, 35.24275, -67.67893]}
        rotation={[1.52042, 1.55192, 1.61621]}
        userData={{ name: "Circle.020" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle021.geometry}
        material={materials["Material.029"]}
        position={[-18.99799, 35.24028, -68.17524]}
        rotation={[1.52042, 1.55192, 1.61621]}
        userData={{ name: "Circle.021" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle022.geometry}
        material={materials["Material.029"]}
        position={[-19.12133, 35.22196, -68.67705]}
        rotation={[1.52042, 1.55192, 1.61621]}
        userData={{ name: "Circle.022" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials["Material.005"]}
        position={[0.2345, 15.92151, -8.01239]}
        scale={[20.06071, 1, 0.49146]}
        userData={{ name: "Cube.026" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials["Material.030"]}
        position={[0.31506, 14.65463, -8.01239]}
        scale={[3.59125, 1.30895, 0.49146]}
        userData={{ name: "Cube.027" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials["Material.008"]}
        position={[4.14864, 10.1925, -7.99]}
        scale={[0.74308, 17.75121, 0.49146]}
        userData={{ name: "Cube.025" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials["Material.007"]}
        position={[5.30654, 10.85663, -7.99]}
        rotation={[0, 0, 1.56479]}
        scale={[0.74308, 3.05542, 0.49146]}
        userData={{ name: "Cube.029" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={materials["Material.011"]}
        position={[-4.60929, 10.91619, -7.99]}
        rotation={[0, 0, 1.56479]}
        scale={[0.74308, 3.2443, 0.49146]}
        userData={{ name: "Cube.030" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials["Material.006"]}
        position={[5.16577, 13.28803, -7.99]}
        rotation={[0, 0, 0.34306]}
        scale={[0.73885, 7.9555, 0.49146]}
        userData={{ name: "Cube.031" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials["Material.010"]}
        position={[-4.59055, 13.34256, -8.00652]}
        rotation={[0, 0, 2.78652]}
        scale={[0.74308, 8.46449, 0.49146]}
        userData={{ name: "Cube.032" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials["Material.003"]}
        position={[6.43766, 10.52086, -7.90703]}
        scale={[0.74308, 18.75061, 0.95196]}
        userData={{ name: "Cube.033" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials["Material.012"]}
        position={[-5.82405, 10.52086, -7.90703]}
        scale={[0.74308, 18.75061, 0.95196]}
        userData={{ name: "Cube.034" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.015"]}
        position={[0.36348, 18.51085, -7.98166]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.80241, 1, 2.13874]}
        userData={{ name: "Plane" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={materials["Material.014"]}
        position={[3.74323, 16.92777, -7.99]}
        rotation={[0, 0, 1.2018]}
        scale={[0.74308, 8.33463, 0.49146]}
        userData={{ name: "Cube.035" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={materials["Material.016"]}
        position={[-3.05537, 16.97978, -7.99]}
        rotation={[0, 0, 1.91986]}
        scale={[0.74308, 8.33463, 0.49146]}
        userData={{ name: "Cube.036" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={materials["Material.018"]}
        position={[3.41404, 19.07649, -8.05979]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.743, 6.31533, 0.37239]}
        userData={{ name: "Cube.037" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038.geometry}
        material={materials["Material.019"]}
        position={[0.32095, 24.0236, -8.09381]}
        scale={[0.743, 8.44086, 0.37239]}
        userData={{ name: "Cube.038" }}
      />
      <group
        position={[0.29036, 20.3886, -7.98166]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.89338, 1, 2.60917]}
        userData={{ name: "Plane.001" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={materials["Material.037"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube039.geometry}
        material={materials["Material.017"]}
        position={[-1.15702, 19.07649, -8.06632]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.743, 6.31533, 0.34476]}
        userData={{ name: "Cube.039" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={materials["Material.004"]}
        position={[3.57949, 19.76515, -8.00273]}
        rotation={[1.49606, -0.9378, 1.5105]}
        scale={[0.74308, 20.43946, 0.74296]}
        userData={{ name: "Cube.041" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube042.geometry}
        material={materials["Material.013"]}
        position={[-2.8505, 19.75575, -8.00155]}
        rotation={[1.48401, 1.03609, 1.64552]}
        scale={[0.74308, 22.07259, 0.74296]}
        userData={{ name: "Cube.042" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle025.geometry}
        material={materials["Material.026"]}
        position={[-21.58769, 46.09618, -61.73546]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.025" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle026.geometry}
        material={materials["Material.026"]}
        position={[-21.17968, 45.70719, -61.79327]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.026" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle027.geometry}
        material={materials["Material.026"]}
        position={[-21.14489, 45.40474, -61.73341]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.027" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle028.geometry}
        material={materials["Material.026"]}
        position={[-20.92359, 45.10298, -61.82827]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.028" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle029.geometry}
        material={materials["Material.026"]}
        position={[-20.81664, 44.74435, -61.77893]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.029" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle030.geometry}
        material={materials["Material.026"]}
        position={[-21.20036, 44.31881, -61.48189]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.030" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle031.geometry}
        material={materials["Material.026"]}
        position={[-20.79235, 43.92982, -61.5397]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.031" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle032.geometry}
        material={materials["Material.026"]}
        position={[-20.75756, 43.62737, -61.47984]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.032" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle033.geometry}
        material={materials["Material.026"]}
        position={[-20.53626, 43.32561, -61.5747]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.033" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle034.geometry}
        material={materials["Material.026"]}
        position={[-20.42931, 42.96698, -61.52536]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.034" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle035.geometry}
        material={materials["Material.026"]}
        position={[-19.97179, 43.07653, -61.71354]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.035" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle036.geometry}
        material={materials["Material.026"]}
        position={[-19.56378, 42.68755, -61.77135]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.036" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle037.geometry}
        material={materials["Material.026"]}
        position={[-19.52899, 42.38509, -61.71148]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.037" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle038.geometry}
        material={materials["Material.026"]}
        position={[-19.30769, 42.08334, -61.80635]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.038" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle039.geometry}
        material={materials["Material.026"]}
        position={[-19.20074, 41.72471, -61.757]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.039" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle040.geometry}
        material={materials["Material.026"]}
        position={[-19.58446, 41.29917, -61.45996]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.040" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle041.geometry}
        material={materials["Material.026"]}
        position={[-19.17645, 40.91018, -61.51778]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.041" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle042.geometry}
        material={materials["Material.026"]}
        position={[-19.14166, 40.60773, -61.45791]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.042" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle043.geometry}
        material={materials["Material.026"]}
        position={[-18.92036, 40.30597, -61.55278]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.043" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle044.geometry}
        material={materials["Material.026"]}
        position={[-18.8134, 39.94734, -61.50343]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.044" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle045.geometry}
        material={materials["Material.026"]}
        position={[-18.79218, 39.62899, -61.57286]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.045" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle046.geometry}
        material={materials["Material.026"]}
        position={[-18.7574, 39.32654, -61.51299]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.046" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle047.geometry}
        material={materials["Material.026"]}
        position={[-18.53609, 39.02478, -61.60785]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.047" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle048.geometry}
        material={materials["Material.026"]}
        position={[-18.42914, 38.66615, -61.55851]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.048" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle049.geometry}
        material={materials["Material.026"]}
        position={[-18.81286, 38.24061, -61.26147]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.049" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle050.geometry}
        material={materials["Material.026"]}
        position={[-18.40485, 37.85163, -61.31929]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.050" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle051.geometry}
        material={materials["Material.026"]}
        position={[-18.37006, 37.54917, -61.25942]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.051" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle052.geometry}
        material={materials["Material.026"]}
        position={[-18.14876, 37.24741, -61.35428]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.052" }}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle053.geometry}
        material={materials["Material.026"]}
        position={[-18.04181, 36.88879, -61.30494]}
        rotation={[1.56585, 1.55195, Math.PI / 2]}
        userData={{ name: "Circle.053" }}
      />
      <group
        position={[4.05483, 20.80555, 2.07728]}
        rotation={[-0.02542, 0.08759, -0.80315]}
        scale={[2.72793, 2.50578, 10.52205]}
        userData={{ name: "Cube" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials["Material.025"]}
        />
      </group>
      <group
        position={[0.64411, 24.73169, -4.55094]}
        rotation={[0, 0.08329, 0]}
        scale={[2.19757, 2.80008, 2.02715]}
        userData={{ name: "Cube.024" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_1.geometry}
          material={materials["Material.034"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_2.geometry}
          material={materials["Material.042"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_3.geometry}
          material={materials["Material.043"]}
        />
      </group>
      <group
        position={[1.22104, 25.02517, 1.65807]}
        rotation={[0, 0.09375, 0]}
        scale={[2.65368, 3.90933, 3.37313]}
        userData={{ name: "Cube.044" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045.geometry}
          material={materials["Material.033"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_1.geometry}
          material={materials["Material.035"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials["Material.008"]}
        position={[-3.43366, 10.34685, -7.99]}
        scale={[0.74308, 17.32727, 0.49146]}
        userData={{ name: "Cube.028" }}
      />
      <group
        position={[11.08328, 20.14886, -4.98514]}
        rotation={[-0.02211, 0, -Math.PI / 2]}
        scale={[0.42399, 1, 0.49085]}
        userData={{ name: "Circle.059" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle059_1.geometry}
          material={materials["Material.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle059_2.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle059_3.geometry}
          material={materials["Material.023"]}
        />
      </group>
      <group
        position={[12.07197, 20.45032, 6.63697]}
        rotation={[-0.02211, 0.02845, -Math.PI / 2]}
        scale={[0.42399, 1, 0.49085]}
        userData={{ name: "Circle.057" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle060_1.geometry}
          material={materials["Material.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle060_2.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle060_3.geometry}
          material={materials["Material.023"]}
        />
      </group>
      <group
        position={[10.1647, 5.3752, -8.2558]}
        rotation={[0, 0.05873, -Math.PI / 2]}
        userData={{ name: "Circle.058" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle061_1.geometry}
          material={materials["Material.044"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle061_2.geometry}
          material={materials["Material.038"]}
        />
      </group>
      <group
        position={[10.77513, 5.3752, 0.3559]}
        rotation={[-0.03289, 0.06361, -1.5687]}
        userData={{ name: "Circle.056" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle062_1.geometry}
          material={materials["Material.044"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle062_2.geometry}
          material={materials["Material.038"]}
        />
      </group>
      <group
        position={[-22.27431, 40.36532, 16.62062]}
        scale={[0.35717, 2.6765, 0.37452]}
        userData={{ name: "Circle.061" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle057_1.geometry}
          material={materials["Material.049"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle057_2.geometry}
          material={materials["Material.050"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube049.geometry}
        material={materials["Material.051"]}
        position={[11.97567, 6.09187, -14.81502]}
        scale={[0.85723, 4.6306, 0.34677]}
        userData={{ name: "Cube.049" }}
      />
      <group
        position={[12.13116, 4.67925, -15.58292]}
        rotation={[-0.02654, 0, 0]}
        userData={{ name: "Circle.067" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle070_1.geometry}
          material={materials["Material.052"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle070_2.geometry}
          material={materials["Material.053"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle070_3.geometry}
          material={materials["Material.054"]}
        />
      </group>
      <group
        position={[11.59168, 4.79278, -16.40969]}
        rotation={[1.77357, 0.02802, -1.43535]}
        scale={[0.1807, 0.13776, 0.15061]}
        userData={{ name: "bicycle" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bicycle_1.geometry}
          material={materials["Material.055"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bicycle_2.geometry}
          material={materials["Material.056"]}
        />
      </group>
      <group
        position={[6.37033, 10.58518, -8.33432]}
        rotation={[-0.81051, 0.05036, 0.12367]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.002" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.78943, 10.11653, -7.85862]}
        rotation={[-1.42463, -0.67303, -1.29768]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.003" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.32466, 9.38289, -8.40512]}
        rotation={[-0.90581, 0.0734, 0.05778]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.004" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.82373, 8.03999, -7.82626]}
        rotation={[-1.5288, -0.72529, -1.56858]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.005" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.84764, 8.86656, -8.05971]}
        rotation={[-1.36153, -0.9571, -1.38524]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.006" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.55566, 8.71711, -8.39882]}
        rotation={[-0.82082, -0.21868, -0.33767]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.007" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.54206, 6.67736, -8.48849]}
        rotation={[-0.50014, -0.3165, -0.31062]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.008" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.9929, 7.52956, -8.19445]}
        rotation={[-1.1449, -1.03583, -1.12864]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.009" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.41705, 7.57018, -8.3773]}
        rotation={[-0.32249, -0.28821, -0.0224]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.010" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.98216, 5.58195, -8.01346]}
        rotation={[-1.26917, -1.12383, -1.23823]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.011" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.73157, 11.26821, -8.37902]}
        rotation={[-0.77543, -0.26814, -0.17492]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.012" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.42784, 12.3541, -8.33968]}
        rotation={[-0.98012, -0.03611, 0.04216]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.013" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.2626, 13.07233, -8.29036]}
        rotation={[-0.97347, 0.41064, -0.53202]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.014" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.54484, 13.27753, -7.7825]}
        rotation={[0.50851, 0.41064, -0.53202]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.015" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.89786, 12.27713, -7.90991]}
        rotation={[-1.30969, -0.71258, -1.31972]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.016" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane016_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.55512, 13.36303, -7.73153]}
        rotation={[0.50851, 0.41064, -0.53202]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.017" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane017_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.80759, 12.92696, -7.89409]}
        rotation={[-1.55726, -0.5881, -1.57922]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.018" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane018_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.85008, 13.5087, -8.44496]}
        rotation={[-0.31887, -0.67234, -0.1534]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.019" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.25842, 13.6538, -8.32299]}
        rotation={[-0.39295, 0.40197, -0.3965]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.020" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.63075, 14.50543, -8.39623]}
        rotation={[-0.76218, 0.63837, 0.17965]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.021" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.84401, 13.84611, -7.84661]}
        rotation={[-1.62122, -0.80613, -1.48211]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.022" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.83689, 10.705, -8.13163]}
        rotation={[-1.20511, -0.82229, -0.96021]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.023" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane023_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane023_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[6.78284, 9.63734, -8.27198]}
        rotation={[-1.06622, -0.45891, -0.7115]}
        scale={[0.21815, 1, 0.37711]}
        userData={{ name: "Plane.024" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane024_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane024_2.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve001.geometry}
        material={materials["Material.047"]}
        position={[6.66422, 5.60496, -7.86674]}
        userData={{ name: "BezierCurve.001" }}
      />
      <group
        position={[33.00489, 8.89221, 33.0749]}
        userData={{ name: "Circle" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={materials["Material.059"]}
        position={[0.21215, 8.00585, -7.98845]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[2.79564, 1, 5.13099]}
        userData={{ name: "Plane.025" }}
      />
      <group
        position={[24.97516, 8.89221, 50.31933]}
        userData={{ name: "Circle.060" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle056_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle056_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[38.96318, 8.89221, 50.31933]}
        userData={{ name: "Circle.062" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle058_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle058_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-11.20142, 8.89221, 50.31933]}
        userData={{ name: "Circle.063" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle063_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle063_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-1.26028, 8.89221, 59.99645]}
        userData={{ name: "Circle.064" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle064_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle064_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[13.29411, 8.89221, 54.22657]}
        userData={{ name: "Circle.065" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle065_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle065_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[4.38794, 8.89221, 44.45924]}
        userData={{ name: "Circle.068" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle066_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle066_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-2.34828, 8.89221, 21.94773]}
        userData={{ name: "Circle.069" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle067_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle067_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-17.33189, 8.89221, 33.47647]}
        userData={{ name: "Circle.070" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle069_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle069_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-3.11618, 8.89221, 33.47647]}
        userData={{ name: "Circle.072" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle072_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle072_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[44.03181, 8.89221, 21.00034]}
        userData={{ name: "Circle.073" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle073_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle073_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[43.893, 8.89221, 37.61065]}
        userData={{ name: "Circle.074" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle074_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle074_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[31.81561, 8.89221, 62.05369]}
        userData={{ name: "Circle.075" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle075_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle075_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[21.36054, 8.89221, 59.02659]}
        userData={{ name: "Circle.076" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle076_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle076_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[42.22364, 8.89221, 59.02659]}
        userData={{ name: "Circle.077" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle077_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle077_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[7.93958, 8.89221, 64.60233]}
        userData={{ name: "Circle.078" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle078_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle078_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-13.88168, 8.89221, 59.99645]}
        userData={{ name: "Circle.079" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle079_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle079_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-1.26028, 8.89221, 51.50849]}
        userData={{ name: "Circle.080" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle080_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle080_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[24.97516, 8.89221, 39.98608]}
        userData={{ name: "Circle.081" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle081_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle081_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[15.27554, 8.89221, 44.76586]}
        userData={{ name: "Circle.082" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle082_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle082_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[53.9663, 8.89221, 59.02659]}
        userData={{ name: "Circle.083" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle083_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle083_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[47.79979, 8.89221, 71.11707]}
        userData={{ name: "Circle.084" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle084_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle084_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[34.07546, 8.89221, 72.77799]}
        userData={{ name: "Circle.085" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle085_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle085_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[4.24134, 10.0807, 77.33704]}
        userData={{ name: "Circle.086" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle086_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle086_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[17.11528, 8.9964, 68.03063]}
        userData={{ name: "Circle.087" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle087_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle087_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[18.59547, 8.89221, 81.30112]}
        userData={{ name: "Circle.088" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle088_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle088_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[28.95522, 8.8799, 81.5358]}
        userData={{ name: "Circle.089" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle089_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle089_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[54.73553, 8.95119, 76.46127]}
        userData={{ name: "Circle.090" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle090_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle090_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-10.63009, 8.89221, 92.68073]}
        userData={{ name: "Circle.091" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle091_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle091_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-8.3799, 9.86316, 71.15764]}
        userData={{ name: "Circle.092" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle092_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle092_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[41.59174, 8.8799, 81.5358]}
        userData={{ name: "Circle.093" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle093_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle093_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-22.83918, 7.73208, 51.59575]}
        userData={{ name: "Circle.094" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle094_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle094_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-31.23625, 7.73208, 36.11131]}
        userData={{ name: "Circle.095" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle095_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle095_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-31.23625, 7.73208, 60.89528]}
        userData={{ name: "Circle.096" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle096_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle096_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-31.23625, 7.73208, 47.59647]}
        userData={{ name: "Circle.097" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle097_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle097_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[10.49556, 8.89221, 81.30112]}
        userData={{ name: "Circle.071" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle098_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle098_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[25.72716, 8.9964, 68.03063]}
        userData={{ name: "Circle.098" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle099_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle099_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-2.90217, 8.89221, 81.30112]}
        userData={{ name: "Circle.099" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle100_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle100_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-18.60555, 8.89221, 81.30112]}
        userData={{ name: "Circle.100" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle101_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle101_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-18.60555, 8.89221, 72.53837]}
        userData={{ name: "Circle.101" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle102_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle102_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-31.23625, 7.73208, 75.29616]}
        userData={{ name: "Circle.102" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle071_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle071_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-41.55937, 7.73208, 42.76265]}
        userData={{ name: "Circle.103" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle103_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle103_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-41.55937, 7.73208, 56.95845]}
        userData={{ name: "Circle.104" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle104_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle104_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-41.55937, 7.73208, 71.28812]}
        userData={{ name: "Circle.105" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle105_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle105_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-41.55937, 7.73208, 84.71189]}
        userData={{ name: "Circle.106" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle106_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle106_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-41.55937, 7.73208, 13.6383]}
        userData={{ name: "Circle.107" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle107_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle107_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-37.95725, 7.73208, 29.26437]}
        userData={{ name: "Circle.108" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle108_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle108_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-24.09274, 7.73208, 6.08117]}
        userData={{ name: "Circle.109" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle109_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle109_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-23.9125, 7.73208, 21.48025]}
        userData={{ name: "Circle.110" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle110_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle110_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-37.23862, 7.73208, 21.48025]}
        userData={{ name: "Circle.111" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle111_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle111_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-48.25267, 7.73208, 21.48025]}
        userData={{ name: "Circle.112" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle112_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle112_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-48.25267, 7.73208, 33.32616]}
        userData={{ name: "Circle.113" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle113_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle113_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-48.25267, 7.73208, 48.07882]}
        userData={{ name: "Circle.114" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle114_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle114_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-55.53491, 7.73208, 41.83703]}
        userData={{ name: "Circle.115" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle115_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle115_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-55.53491, 7.73208, 28.86924]}
        userData={{ name: "Circle.116" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle116_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle116_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-55.53491, 7.73208, 17.07714]}
        userData={{ name: "Circle.117" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle117_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle117_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-55.53491, 7.73208, 51.97502]}
        userData={{ name: "Circle.118" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle118_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle118_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-55.53491, 7.73208, 59.9552]}
        userData={{ name: "Circle.119" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle119_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle119_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-47.7559, 7.73208, 59.9552]}
        userData={{ name: "Circle.120" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle120_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle120_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-47.7559, 7.73208, 53.32478]}
        userData={{ name: "Circle.121" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle121_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle121_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-47.7559, 7.73208, 67.75693]}
        userData={{ name: "Circle.122" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle122_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle122_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-61.71888, 7.73208, 47.58419]}
        userData={{ name: "Circle.123" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle123_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle123_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-19.15056, 7.73208, 14.26237]}
        userData={{ name: "Circle.124" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle124_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle124_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-12.36138, 7.73208, 20.07392]}
        userData={{ name: "Circle.125" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle125_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle125_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-12.36138, 7.73208, 28.39263]}
        userData={{ name: "Circle.126" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle126_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle126_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-25.28226, 7.73208, 29.26437]}
        userData={{ name: "Circle.127" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle127_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle127_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-25.28226, 7.73208, 41.8772]}
        userData={{ name: "Circle.128" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle128_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle128_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-31.64655, 7.73208, 19.6279]}
        userData={{ name: "Circle.129" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle129_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle129_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-13.30748, 8.89221, 42.26807]}
        userData={{ name: "Circle.130" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle130_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle130_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-61.98363, 7.73208, 35.61879]}
        userData={{ name: "Circle.131" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle131_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle131_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-41.87149, 7.73208, 35.78382]}
        userData={{ name: "Circle.132" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle132_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle132_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-9.24831, 3.75758, 2.47376]}
        scale={[241.40677, 2.92773, 250.58125]}
        userData={{ name: "Cube.018" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_2.geometry}
          material={materials["Material.048"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath.geometry}
        material={materials["Material.060"]}
        position={[-2.28481, 4.50165, -32.89498]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-106.43543, -1.68006, -20.18343]}
        userData={{ name: "NurbsPath" }}
      />
      <group
        position={[-38.72083, 9.22342, 49.51962]}
        userData={{ name: "Circle.133" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle133_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle133_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={materials["Material.062"]}
        position={[0.18929, 4.66241, -19.96793]}
        scale={[7.88118, 7.88118, 24.66624]}
        userData={{ name: "Plane.026" }}
      />
      <group
        position={[-28.21354, 6.86166, 68.4507]}
        userData={{ name: "Circle.134" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle134_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle134_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-38.8181, 7.94923, 63.66011]}
        userData={{ name: "Circle.135" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle135_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle135_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-24.77294, 6.38073, 62.17979]}
        userData={{ name: "Circle.136" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle136_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle136_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-33.25555, 7.20932, 54.49461]}
        userData={{ name: "Circle.137" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle137_1.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle137_2.geometry}
          material={materials["Material.058"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Villa.glb");
